# Generated by Django 4.1.4 on 2022-12-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('rfid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cup_size', models.CharField(choices=[('S', 'SINGLE'), ('D', 'DOUBLE')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.configuration')),
            ],
        ),
    ]
