# Generated by Django 4.1.4 on 2022-12-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=20)),
                ('cup_size', models.CharField(choices=[('S', 'SIMPLE'), ('D', 'DOUBLE')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='tokens',
            name='rfid',
        ),
        migrations.DeleteModel(
            name='RFID',
        ),
        migrations.AlterField(
            model_name='coffeeauthenication',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.configuration'),
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
